services:
  repower-consume-service:
    container_name: repower-consume-service
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8103:8000"
    environment:
      DJANGO_SECRET_KEY: 'your-secret-key'
      DJANGO_DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DJANGO_DB_ENGINE: 'django.db.backends.sqlite3'
      DJANGO_DB_NAME: '/app/db.sqlite3'