services:
  repower-consume-service:
    container_name: repower-consume-service
    build: .
    #command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8103:8000"
    env_file:
      - /home/vmuser/REPOWER/Runner/.env